### ISSUE TITLE
Scale "Get Started Today" Along with Title and Image to fit on Mobile & Smaller Monitors.  

### ISSUE THREAD

**Issue by NeilShah2026** [InSight3D/MyCoin#5]
![Screenshot 2022-05-26 053953](https://user-images.githubusercontent.com/78612612/170462257-680a7ecb-41c2-4927-ac6d-8b98dbb006ba.png)
Looks a little too large and uneven (align up logo with text).

**Comment by NeilShah2026** [comment]
Also, maybe we can move the while "MyCoin by InSight3D" down ~140px.

**Comment by sbelka-1703** [comment]
Hey, just saw your comment. I applied the fix to your two comments above
